"""analytics_updates

Revision ID: ad17d0f5a71a
Revises: 7b315db48a1a
Create Date: 2026-04-22 16:00:54.388862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad17d0f5a71a'
down_revision: Union[str, Sequence[str], None] = '7b315db48a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_anime_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anilistId', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('trending', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anilistId'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilistId', 'date', name='uq_anime_daily_stats')
    )
    op.create_index('idx_daily_anime_stats_date', 'daily_anime_stats', ['date'], unique=False)
    op.create_table('user_watch_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_anime_watched', sa.Integer(), nullable=True),
    sa.Column('total_episodes_watched', sa.Integer(), nullable=True),
    sa.Column('total_watch_time_sec', sa.Integer(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_watch_stats')
    )
    op.alter_column('activity_feed', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='"metadata"::jsonb')
    op.alter_column('anime_metadata', 'studios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"studios"::jsonb')
    op.alter_column('anime_metadata', 'genres',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"genres"::jsonb')
    op.alter_column('anime_metadata', 'recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"recommendations"::jsonb')
    op.alter_column('anime_metadata', 'nextAiringEpisode',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"nextAiringEpisode"::jsonb')
    op.alter_column('collections', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Tracks the latest episode number watched (can be fractional like 12.5)',
               existing_nullable=False)
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"metadata"::jsonb')
    op.alter_column('payment_logs', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"raw_payload"::jsonb')
    op.alter_column('video_cache', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='"payload"::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_cache', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='"payload"::json')
    op.alter_column('payment_logs', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"raw_payload"::json')
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"metadata"::json')
    op.alter_column('collections', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Tracks the latest episode number watched (can be fractional like 12.5)',
               existing_nullable=False)
    op.alter_column('anime_metadata', 'nextAiringEpisode',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"nextAiringEpisode"::json')
    op.alter_column('anime_metadata', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"recommendations"::json')
    op.alter_column('anime_metadata', 'genres',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"genres"::json')
    op.alter_column('anime_metadata', 'studios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='"studios"::json')
    op.alter_column('activity_feed', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='"metadata"::json')
    op.drop_table('user_watch_stats')
    op.drop_index('idx_daily_anime_stats_date', table_name='daily_anime_stats')
    op.drop_table('daily_anime_stats')
    # ### end Alembic commands ###
