"""domain_3_health_metrics

Revision ID: c629964e0aa9
Revises: dd60be6dc1b6
Create Date: 2026-04-22 16:15:44.829112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c629964e0aa9'
down_revision: Union[str, Sequence[str], None] = 'dd60be6dc1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('episodes_attempted', sa.Integer(), nullable=True),
    sa.Column('episodes_success', sa.Integer(), nullable=True),
    sa.Column('episodes_failed', sa.Integer(), nullable=True),
    sa.Column('avg_ingest_duration_sec', sa.Float(), nullable=True),
    sa.Column('error_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'provider_id', name='uq_ingestion_metrics_date_provider')
    )
    op.create_table('provider_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('is_reachable', sa.Boolean(), nullable=True),
    sa.Column('avg_response_ms', sa.Float(), nullable=True),
    sa.Column('success_rate_7d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_health')
    op.drop_table('ingestion_metrics')
    # ### end Alembic commands ###
